Feature/#52 팔로우, 팔로잉한 유저 리스트를 가져오는 기능을 구현한다.
Busan-Dinosaur/FoodBowl-Server pull request #101
Opened 2023-02-11 07:20 UTC by JeonghakLee

## 🔥 연관 이슈

close: #23 

## 📝 작업 요약
팔로우, 언팔로우 기능을 Follow 객체가 관리하도록 수정하였습니다.
팔로우, 팔로잉한 유저 목록을 가져오는 기능을 구현하였습니다.

## 🔎 작업 상세 설명
기존에 User가 @OneToMany를 통해 관리하던 Follow 객체 및 관련 기능들을 Follow가 관리하도록 수정하였습니다. 이유는
- 인스타그램을 보면 팔로워가 천만명이상인 경우도 있는데 만약에 그런일이 생긴다면 List로는 관리하기 어렵다고 생각했습니다.
- 유저가 Follower, Follwing을 List로 관리하면 목록을 페이징하여 가져오려면 결국 조회하는 기능은 새로 구현해야 했습니다.
- 
## 🌟 리뷰 요구 사항

2023-02-14 00:58 UTC, woo-chang requested changes
열심히 작성하신만큼 혼신의 힘을 담아 리뷰했습니다 ⛄️

2023-02-14 00:58 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/domain/follow/api/FollowController.java
> +  public ResponseEntity<List<FollowGetResponseDto>> getFollowers(
`id` 앞에는 해당 리소스가 와야한다고 생각했는데, 인스타그램에서도 정학님이 하신 것과 동일한 `uri`를 사용하네요!

`uri`에 대해 다시 한번 생각해볼 수 있었습니다. 되게 잘 작성하신 것 같습니다 👍👍

2023-02-14 00:58 UTC, woo-chang commented on src/test/java/com/dinosaur/foodbowl/domain/follow/api/FollowControllerTest.java
> +              .param("size", "2"))
`pages`? `page` 아닌가요? 정말 궁금해서 물어보는겁니다!

2023-02-14 00:58 UTC, woo-chang commented on src/test/java/com/dinosaur/foodbowl/domain/follow/api/FollowControllerTest.java
> +              .param("size", "2"))
`0`과 `2`를 지정해준 이유가 있을까요? 특별한 이유가 존재하지 않는다면 디폴트 값으로 사용해봐도 좋을 것 같아요 :)

2023-02-14 00:58 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/domain/follow/api/FollowController.java
> +    List<FollowGetResponseDto> response = getFollowService.getFollowers(user, pageable);
**질문사항 입니다!**
1. 위와 같이 유저 조회와 팔로워, 팔로잉 조회를 분리하면 트랜잭션이 안 끊기고 연속적으로 수행되는지, 아니면 2개의 트랜잭션이 동작하는지 궁금합니다!
2. 트랜잭션이 2개가 동작한다면 user가 영속성 컨텍스트에서 벗어나서 의도하지 않은 동작이 수행되거나, user를 다시 조회하게 될까요?
3. 트랜잭션 연속적으로 동작한다면 service 안에서 findService를 호출하지 않고 controller에서 분기를 나눈 이유가 있을까요?

2023-02-14 00:58 UTC, woo-chang commented on src/test/java/com/dinosaur/foodbowl/domain/follow/api/FollowControllerTest.java
> +  }
기능에 대한 질문사항과 연결되는 내용입니다.

조회하고자 하는 유저가 존재하지 않을 경우에 대한 테스트도 필요해보입니다!

2023-02-14 07:56 UTC, JeonghakLee commented on src/main/java/com/dinosaur/foodbowl/domain/follow/api/FollowController.java
> +    List<FollowGetResponseDto> response = getFollowService.getFollowers(user, pageable);
1. 각각 다른 service에서 Transaction을 걸고 있어서 2개가 동작할 것 같습니다
2. User를 한 트랜잭션에서 이미 읽어 왔고 해당 트랜잭션은 종료된 후, user 인스턴스를 getFollowers에서 넘겨 받은 채로 새 트랜잭션이 실행되기 때문에 그런일은 발생하지 않을 것 같은데 어떻게 생각하시나요? 
3. Service 간의 의존도를 줄이기 위해서 사용했습니다

2023-02-14 07:56 UTC, JeonghakLee commented on src/main/java/com/dinosaur/foodbowl/domain/user/dao/UserRepository.java
> +  List<User> findFollowersByUser(@Param("user") User user, Pageable pageable);
`User`를 찾아오는 일이라 여기서 하긴 했는데 follow repository에서 하는게 더 나을까요?

2023-02-14 07:59 UTC, JeonghakLee commented on src/test/java/com/dinosaur/foodbowl/domain/follow/api/FollowControllerTest.java
> +              .param("size", "2"))
page로 하니까 오류가나서 pages인걸로 알았는데 아닌가요?...

2023-02-14 08:36 UTC, JeonghakLee commented on src/main/java/com/dinosaur/foodbowl/domain/follow/dto/FollowGetResponseDto.java
> +  private String nickName;
이미 맞팔인걸 표시해줄 수 있어서 있으면 좋을 것 같습니다!

2023-02-16 08:19 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/domain/user/dao/UserRepository.java
> +  List<User> findFollowersByUser(@Param("user") User user, Pageable pageable);
그거는 생각지도 못했네요 .. ! 너무 좋습니다 👍👍

그렇다면 매개변수로 찾고자 하는 `user`를 전달하고 있으므로 `ByUser`의 의미는 담지 않아도 의미를 파악할 수 있을 것 같습니다.
따라서 네이밍을 `findFollowersByUser` -> `findFollowerUsers`로 변경하는건 어떨까요?

2023-02-16 08:31 UTC, woo-chang commented on src/test/java/com/dinosaur/foodbowl/domain/follow/api/FollowControllerTest.java
> +              .param("size", "2"))
`http://localhost:8080/users/?page=3&size=4`

위와 같이 `page`로 요청합니다 .. ! 혹시 어떤 오류가 발생하나요? 🤔

2023-02-16 08:33 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/domain/follow/api/FollowController.java
> +    List<FollowGetResponseDto> response = getFollowService.getFollowers(user, pageable);
2. 말씀하신대로 트랜잭션이 2개 동작한다면 트랜잭션마다 다른 영속성 컨텍스트를 사용하기에 오류 발생가능성이 존재하지 않나요?
3. 의존도를 줄이기 위해 사용한 것은 좋습니다 👍👍 하지만 위의 상황이 어떻게 진행되는지 검증이 필요해 보입니다!

2023-03-06 03:32 UTC, woo-chang approved these changes
정말 정말 수고하셨습니다 감사합니다 :) 👍👍

2023-03-06 03:32 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/domain/follow/application/FollowService.java
> +    follow.ifPresent(followRepository::delete);
너무 좋은데요 👍👍

2023-03-06 03:32 UTC, merged