Feature/#5 user 테이블 설계
Busan-Dinosaur/FoodBowl-Server pull request #21
Opened 2023-01-03 13:51 UTC by gusah009

## 🔥 Related Issue

close: #5

## 📝 Description

1. User Entity 생성 및 관련 기반 Entity들 생성
2. 관련 Test도 생성해봤음

## 🌟 Review

PM 화이팅 이정학 화이팅!

2023-01-03 14:20 UTC, woo-chang requested changes

2023-01-03 17:57 UTC, woo-chang commented on src/test/java/com/dinosaur/foodbowl/domain/user/repository/UserRepositoryTest.java
> +        .toString();
컨벤션이 조금 불편합니다 ㅎㅎ

2023-01-03 23:05 UTC, gusah009 commented on src/main/java/com/dinosaur/foodbowl/domain/user/entity/User.java
> +  public static final int MAX_INTRODUCE_LENGTH = 255;
해당 상수들은 테스트용으로 둔 게 아니라, User 관련 도메인 정보를 상수화 한 것이었습니다.

지금 생각해보니 딱히 필요 없을 것 같기도 하네요! DB에서 길이 제한은 잡아주기도 하니 테스트로 옮겨야겠습니다!

굿굿! 👍👍

2023-01-03 23:07 UTC, gusah009 commented on src/test/java/com/dinosaur/foodbowl/domain/user/repository/UserRepositoryTest.java
> +  @Nested
테스트 할 때 아래와 같이 나와서 보기에도 좋고, 엄청 길어진 테스트 코드 속에서 조금이라도 더 디렉토리화 시킨 것으로 이해해주시면 좋겠습니다!

<img width="320" alt="image" src="https://user-images.githubusercontent.com/26597702/210456143-237f4c10-78f3-46f0-9391-b6aaa09bc932.png">

2023-01-03 23:08 UTC, gusah009 commented on src/test/java/com/dinosaur/foodbowl/domain/user/repository/UserRepositoryTest.java
> +}
저는 그래서 도입한게 `@Nested`였습니다.

같은 도메인 로직인데 다른 파일에 있는 것 보다 붙여 놓는게 코드 재활용성이나 한 눈에 보기에도 좋을 것 같다고 생각했습니다!

2023-01-03 23:09 UTC, gusah009 commented on src/test/java/com/dinosaur/foodbowl/domain/user/repository/UserRepositoryTest.java
> +        .toString();
놀랍게도 IDE 포맷팅 그대로 맞춘건데, 한 줄에 쓰는게 나을까요??

2023-01-03 23:48 UTC, JeonghakLee approved these changes

2023-01-04 02:42 UTC, woo-chang commented on src/test/java/com/dinosaur/foodbowl/domain/user/repository/UserRepositoryTest.java
> +  @Nested
오옹 좋습니다 👏🏻👏🏻

2023-01-04 02:43 UTC, woo-chang commented on src/test/java/com/dinosaur/foodbowl/domain/user/repository/UserRepositoryTest.java
> +        .toString();
그렇다면 그대로 가는게 좋을 것 같습니다 !

2023-01-04 02:44 UTC, woo-chang approved these changes
수고하셨습니다 👍👍

2023-01-04 02:46 UTC, merged