Feature/#19 팔로우 팔로우취소 기능 구현
Busan-Dinosaur/FoodBowl-Server pull request #67
Opened 2023-01-18 01:33 UTC by JeonghakLee

## 🔥 Related Issue

close: #19 

## 📝 Description

팔로우 & 팔로우 취소 기능 구현
API 문서작성

## 🌟 Review
ㅜㅜ

2023-01-18 02:08 UTC, gusah009 requested changes
수고 많으셨습니다~!

2023-01-18 02:08 UTC, gusah009 commented on src/test/java/com/dinosaur/foodbowl/domain/follow/api/FollowControllerTest.java
> +public class FollowControllerTest extends ControllerTest {
서비스에서 유저를 못 찾았을 때, 내가 나를 팔로우 했을때, 이미 팔로우 한 사람일 때 등등 여러 분기에서 `Exception`이 터지는 걸로 알고 있습니다.

각각의 `Exception`이 터졌다고 가정하고 어떤 응답을 반환하는지도 `ControllerTest`에 있으면 좋을 것 같습니다!

2023-01-18 02:08 UTC, gusah009 commented on src/docs/follow/follow.adoc
> +include::{snippets}/unfollow/response-body.adoc[]
`204`를 반환하는데 `Response Body`가 필요한가요?

2023-01-18 02:23 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/domain/follow/application/FollowService.java
> +  private final AuthUtil authUtil;
`AuthUtil` 사용하지 않는 것 같습니다!

2023-01-18 02:23 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/domain/follow/application/FollowService.java
> +  private void checkAlreadyFollowed(User me, User other) {
`User`에서 `cascade`로 `Following`이랑 `Follower`를 관리하는 방법은 어떨까요?

2023-01-18 02:23 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/domain/follow/entity/Follow.java
> +  }
직접 만들어서 사용하신다면 `@EqualsAndHashCode` 어노테이션은 제거해도 좋을 것 같습니다!

2023-01-18 02:23 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/domain/follow/entity/Follow.java
> +  }
해당 메서드도 여기보다는 `User`에 위치하는게 맞는것 같습니다!

2023-01-18 02:23 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/domain/user/entity/User.java
> +  }
`@ToString` 적용되어있는데 다시 재정의하신 이유가 있을까요? ?

2023-01-18 02:23 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/domain/follow/entity/Follow.java
> +  }
동일한 `User`를 매개변수로 받는 경우 사용하는 입장에서 헷갈릴 수 있기 때문에

`builder`를 직접 사용하는게 오류를 줄일 수 있다고 생각하는데 이 점은 어떻게 생각하시나요?

2023-01-18 02:23 UTC, woo-chang commented on src/test/java/com/dinosaur/foodbowl/domain/follow/application/FollowServiceTest.java
> +  @DisplayName("성공 테스트")
성공 테스트와 실패 테스트를 나눠서 명확해진 것 같습니다 👍👍

2023-01-18 02:23 UTC, woo-chang commented on src/test/java/com/dinosaur/foodbowl/domain/follow/application/FollowServiceTest.java
> +      System.out.println("여기1" + all1);
`all1`이라는 변수명은 조금 그렇습니다! ㅋㅋㅋㅋㅎㅎ

불필요한 출력문도 포함되어 있습니다!

2023-01-18 02:23 UTC, woo-chang commented on src/test/java/com/dinosaur/foodbowl/domain/follow/application/FollowServiceTest.java
> +      System.out.println("여기" + all);
요기도 위와 동일합니다.

2023-01-18 02:23 UTC, woo-chang commented on src/test/java/com/dinosaur/foodbowl/domain/follow/application/FollowServiceTest.java
> +          IllegalArgumentException.class);
`Exception`도 실패한 이유를 알려줄 수 있게 @gusah009 님이 사용하신 방법을 사용해봐도 좋을 것 같아요 !!

2023-01-18 02:34 UTC, JeonghakLee commented on src/main/java/com/dinosaur/foodbowl/domain/follow/application/FollowService.java
> +  }
원래 팔로우한 사람을 요청하는 것 자체가 발생하면 안되는 일이라 클라이언트에서 알 필요가 있지 않나해서 클라이언트에러를 발생하도록 하려 했는데 크리티컬하진 않아서 우선 그냥 반환하도록 하겠습니다!

2023-01-18 02:35 UTC, JeonghakLee commented on src/test/java/com/dinosaur/foodbowl/domain/follow/application/FollowServiceTest.java
> +  private AuthUtil authUtil;
개행도 꼼꼼히 확인해서 commit 하겠습니다..!

2023-01-18 02:35 UTC, JeonghakLee commented on src/test/java/com/dinosaur/foodbowl/domain/follow/api/FollowControllerTest.java
> +public class FollowControllerTest extends ControllerTest {
좋은 의견 감사합니다 최고!!

2023-01-18 02:36 UTC, JeonghakLee commented on src/docs/follow/follow.adoc
> +include::{snippets}/unfollow/response-body.adoc[]
반환 값이 없다는 것을 명시하려고 했는데 굳이 필요 없을 수 있겠네요!

2023-01-18 02:38 UTC, JeonghakLee commented on src/main/java/com/dinosaur/foodbowl/domain/follow/application/FollowService.java
> +  }
좋은 것 같습니다! @ImageOrNull을 참고해 보도록 하겠습니다

2023-01-18 02:39 UTC, gusah009 commented on src/main/java/com/dinosaur/foodbowl/domain/follow/application/FollowService.java
> +  private void checkAlreadyFollowed(User me, User other) {
https://github.com/Busan-Dinosaur/FoodBowl-Server/pull/60 여기에서 만들어뒀습니다!

2023-01-18 02:40 UTC, gusah009 commented on src/main/java/com/dinosaur/foodbowl/domain/follow/entity/Follow.java
> +  }
`@EqualsAndHashCode(of = {"following", "follower"}, callSuper = false)` 로 사용하면 안되나요?

2023-01-18 02:41 UTC, JeonghakLee commented on src/main/java/com/dinosaur/foodbowl/domain/follow/entity/Follow.java
> +  }
파라미터의 타입이 같고 순서가 중요한 경우 충분히 그럴 수 있겠네요ㄷㄷ 
동의합니다!

2023-01-18 02:44 UTC, JeonghakLee commented on src/main/java/com/dinosaur/foodbowl/domain/user/entity/User.java
> +  }
..분명 지웠는데..!

2023-01-18 02:46 UTC, JeonghakLee commented on src/test/java/com/dinosaur/foodbowl/domain/follow/application/FollowServiceTest.java
> +      System.out.println("여기1" + all1);
이후 커밋에서 지웠습니다..!ㅎㅎ

2023-01-18 12:41 UTC, JeonghakLee commented on src/main/java/com/dinosaur/foodbowl/domain/follow/application/FollowService.java
> +  private void checkMe(User me, Long userId) {
그럼 service에서 또 userId를 통해 user를 가져와서 비교를 해야한다는 문제가 있습니다! 
이부분 삭제하고 @gusah009 님 의견에 따라 컨트롤러 단에서 자기 자신에 대한 팔로우를 처리하는 어노테이션을 만들어 처리하고자 합니다!

2023-01-18 14:22 UTC, gusah009 commented on src/main/java/com/dinosaur/foodbowl/domain/follow/application/FollowService.java
> +    User other = userFindDao.findById(otherId);
가독성과 코드 간소화를 모두 잡으셨네요..! 👍👍

> cf6633b140d663c79453ab545c6c9cb044787901 커밋 메시지도 명확해서 읽기 편했습니다!

2023-01-19 03:01 UTC, woo-chang reviewed
수고하셨습니다 👍👍

2023-01-19 03:01 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/domain/follow/api/FollowController.java
> +@Validated
클래스 레벨에 해당 어노테이션을 붙이면 어떤 일이 발생하나요?

2023-01-19 03:05 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/domain/follow/application/FollowService.java
> +  }
한번 더 검증하는 역할인가요? ?

`Exception`은 바꿔야할 것 같습니다!

2023-01-19 04:14 UTC, JeonghakLee commented on src/main/java/com/dinosaur/foodbowl/global/util/validator/follow/IsMeValidator.java
> +      context.buildConstraintViolationWithTemplate("자신에 대한 요청은 불가능합니다.")
`ConstraintViolationException` 이 발생합니다 (`ConstraintViolationException` ->   `ValidationException` -> `RuntimeException`)

2023-01-19 04:46 UTC, JeonghakLee commented on src/main/java/com/dinosaur/foodbowl/domain/follow/api/FollowController.java
> +@Validated
우선 클래스 레벨에 @Validated를 설정하지 않았을 때 테스트에서 @NotMe 의 동작을 확인 할 수 없어서 적용하였습니다. 
[참고](https://velog.io/@heehee/Spring-Bean-validation-%EB%BD%90%EB%82%98%EA%B2%8C-%EC%8D%A8%EB%B3%B4%EC%A7%80-%EC%95%8A%EC%9D%84%EB%9E%98)
> 클래스 레벨에 해당 어노테이션을 붙이면 어떤 일이 발생하나요?
 AOP(Aspect Oriented Programming)을 기반으로 메서드의 요청을 가로채서 유효성 검증을 진행합니다.

2023-01-19 05:06 UTC, JeonghakLee commented on src/main/java/com/dinosaur/foodbowl/domain/follow/application/FollowService.java
> +  }
지웠습니다..!ㅎㅎ

2023-01-19 11:15 UTC, gusah009 approved these changes
`ExceptionHandler`만 한 곳으로 모으면 될 것 같네요!! 미리 approve 하겠습니다~!

2023-01-20 01:59 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/global/error/ExceptionAdvice.java
> +  public Map validationExceptionHandler(ConstraintViolationException e) {
`Map` 말고 `ResponseEntity`를 사용하도록 변경하면 좋을 것 같습니다!

2023-01-20 02:43 UTC, gusah009 approved these changes
편안

2023-01-20 02:53 UTC, woo-chang approved these changes
수고하셨습니다 👍👍

2023-01-20 02:55 UTC, merged