Feature/#16 로그인 로그아웃
Busan-Dinosaur/FoodBowl-Server pull request #73
Opened 2023-01-20 07:33 UTC by woo-chang

## 🔥 Related Issue

close: #16
close: #55

## 📝 Description

- Refresh Token 도입
- 로그인, 로그아웃, 토큰 재발급 기능 구현
- 테스트 코드 간소화

## 🌟 Review

따끔한 리뷰 부탁드립니다!

2023-01-21 00:21 UTC, gusah009 requested changes
처음 기획하셨던 내용이랑 로직이 조금 다른 것 같습니다!

프론트에서 신경쓰지 않아도 되게끔 AT가 만료되면 RT를 보고 AT와 RT를 함께 갱신해주는걸로 알고 있었는데  코드상으론 `/refresh`라는 API로 갱신해주는 것 같더라구요!

기획이 바뀐거라면 커멘트로 알려주시면 감사하겠습니다!

2023-01-21 00:21 UTC, gusah009 commented on src/main/java/com/dinosaur/foodbowl/domain/auth/api/AuthController.java
> +  }
`refresh token`을 발급 받는 API를 만들기 보다 필터에서 접근 시 Token이 만료되었다면 자동으로 setCookie로 refresh token을 갱신해주는 로직이 있는 게 더 나을 것 같습니다!

2023-01-21 00:21 UTC, gusah009 commented on src/main/java/com/dinosaur/foodbowl/domain/auth/application/TokenService.java
> +  }
해당 내용이 `jwtTokenProvider`에 있는 걸로 알고 있습니다! 그 쪽 로직을 수정하시는건 어떨까요?

2023-01-21 00:21 UTC, gusah009 commented on src/main/java/com/dinosaur/foodbowl/domain/auth/application/TokenService.java
> +        .set(String.valueOf(userId), token, REFRESH_TOKEN_VALID_MILLISECOND, TimeUnit.MILLISECONDS);
`String`으로 감싸준 이유가 있을까요?

2023-01-25 03:10 UTC, JeonghakLee reviewed
굿굿 고생하셨습니다!! 탈퇴 회원의 토큰 처리는 아직 논의된게 없는 거죠?

2023-01-25 03:16 UTC, woo-chang commented on src/test/java/com/dinosaur/foodbowl/domain/user/UserTestHelper.java
> +          .introduce(introduce)
`null`이 허용되어 있기에 필수값을 제거했는데 `default` 값이 있는 것이 좋을까요? 🤔

2023-01-25 03:18 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/domain/auth/application/AuthService.java
> +    }
`User`에 추가하는 건 매우 동의합니다 👍🏻

`Bean`으로 등록되어 있는 `PasswordEncoder`를 매개변수로 넘겨주는건 괜찮은지 궁금합니다!

2023-01-25 03:20 UTC, woo-chang commented on src/test/java/com/dinosaur/foodbowl/domain/auth/api/AuthControllerTest.java
> +    void fail_login_by_not_exist_loginId() throws Exception {
테스트 의미를 담기 위해서는 메서드명이 길어지는데, 길어지는 경우 `camel`보다 `snake`가 직관적인 느낌을 저는 받았습니다.

그래서 저도 바꾸려고 했는데 통일하는게 좋을 것 같습니다 👍🏻

`Nit`는 무슨 의미인가요?

2023-01-25 03:20 UTC, woo-chang commented on src/test/java/com/dinosaur/foodbowl/domain/auth/api/AuthControllerTest.java
> +      doNothing().when(tokenService).saveToken(anyLong(), anyString());
좋은 리뷰 감사합니다 👏🏻👏🏻

2023-01-25 03:21 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/global/config/security/jwt/JwtTokenProvider.java
> +  public String extractToken(HttpServletRequest req, String tokenName) {
너무 너무 좋은 것 같습니다! 메서드의 모호함을 제거해주는 `Enum` 짱

2023-01-25 03:22 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/domain/auth/api/AuthController.java
> +  }
저의 불찰 ... 동의합니다 👍🏻

2023-01-25 03:23 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/domain/auth/application/TokenService.java
> +  }
`tokenValidatioDto`를 반환받지 말고 바로 예외가 발생하도록 수정하라는 말씀이신가요? 🤔

2023-01-25 03:24 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/domain/auth/application/TokenService.java
> +        .set(String.valueOf(userId), token, REFRESH_TOKEN_VALID_MILLISECOND, TimeUnit.MILLISECONDS);
`RedisTemplate`의 `key` 타입을 `String`으로 지정해두었기에 `Wrapping` 해주었습니다!

2023-01-25 06:56 UTC, gusah009 commented on src/test/java/com/dinosaur/foodbowl/domain/user/UserTestHelper.java
> +          .introduce(introduce)
아하 `null` 허용이면 `null`로 두어도 괜찮을 것 같네요! 필요하면 헬퍼 사용자가 추가하면 되니깐요

2023-01-25 06:57 UTC, gusah009 commented on src/main/java/com/dinosaur/foodbowl/domain/auth/application/AuthService.java
> +    }
어떤게 좋은지를 떠나서 매개변수로 넘겨주지 않고 마땅히 `PasswordEncoder`를 넘겨줄 방법이 없더라구요..!

2023-01-25 06:59 UTC, gusah009 commented on src/test/java/com/dinosaur/foodbowl/domain/auth/api/AuthControllerTest.java
> +    void fail_login_by_not_exist_loginId() throws Exception {
> test method에서만 snakeCase를 사용하시는 이유가 있으신가요??

https://dzone.com/articles/7-popular-unit-test-naming 별 이유는 없고 전 5번 규칙이 직관적이어서 따르고 있습니다!

> Nit는 무슨 의미인가요?

https://yoon-jj.tistory.com/m/10 저도 이런거 한 번 따라해봤습니닿ㅎㅎ

2023-01-25 08:05 UTC, gusah009 commented on src/main/java/com/dinosaur/foodbowl/domain/auth/application/TokenService.java
> +  }
지금 보니 무슨 커멘트인지 저도 이해하기 어렵네요.. ㅋㅋㅋㅋ 무시해주시면 감사하겠습니다 (_ _)

2023-01-25 09:01 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/domain/auth/application/AuthService.java
> +    }
저의 의도는 `PasswordEncoder`도 하나의 도메인으로 보고 `User` 값을 받아서 서비스단에서 비교하는게 괜찮은지,

`User` 도메인의 역할로 보고 넘겨주는게 괜찮은지 궁금했었습니다!

2023-01-26 00:14 UTC, gusah009 commented on src/main/java/com/dinosaur/foodbowl/domain/auth/application/AuthService.java
> +    }
아하 레이어드 계층은 항상 그 역할 구분을 잘 모르겠네요...

우창님 말씀을 듣고 보니 `PasswordEncoder`를 넘겨주는 것 보다 인코딩된 password를 넘겨주도록 하는 게 맞는 것 같습니다!

2023-01-26 00:20 UTC, JeonghakLee commented on src/main/java/com/dinosaur/foodbowl/domain/auth/application/CookieService.java
> +  }
NIT: DB에 접근하지 않는 service들은 util로 구분해도 괜찮을 것 같은데 어떻게 생각하시나요??

2023-01-26 00:20 UTC, JeonghakLee commented on src/main/java/com/dinosaur/foodbowl/domain/auth/application/CookieService.java
> +@Transactional(readOnly = true)
@Transactional이 필요한 이유가 궁금합니다!

2023-01-26 00:20 UTC, JeonghakLee commented on src/main/java/com/dinosaur/foodbowl/global/config/security/SecurityConfiguration.java
> +  private final JwtAuthenticationFilter jwtAuthenticationFilter;
어느 부분이 생성자 주입 방식으로 변경된 것인지 설명 부탁드립니다!

2023-01-26 00:20 UTC, JeonghakLee commented on src/main/java/com/dinosaur/foodbowl/global/config/security/jwt/JwtAuthenticationFilter.java
> +          refreshTokenValidation.getToken())) {
Nit: boolean을 반환하는 isValid 와 validate 메서드 명을 통일해주는 것도 좋을 것 같습니다!

2023-01-26 00:25 UTC, gusah009 reviewed
`JwtAuthenticationFilter`에서 하는 역할이 너무 많은 것 같은데, `RefreshTokenFilter` 같은 필터를 하나 더 두는 건 어떻게 생각하시나요?

Ex) https://github.com/KEEPER31337/Homepage-Back-R2/pull/28

2023-01-26 00:25 UTC, gusah009 commented on src/main/java/com/dinosaur/foodbowl/domain/auth/api/AuthController.java
> +  }
요 친구는 어떤 기능을 하는 API 일까요??

2023-01-26 00:25 UTC, gusah009 commented on src/main/java/com/dinosaur/foodbowl/domain/auth/api/AuthController.java
> +        (int) REFRESH_TOKEN.getValidMilliSecond() / 1000);
`cookieService.generateCookie()`에 `expired`에 시간 단위가 나와 있지 않아서 나중에 사용하는 사람들은 헷갈릴 수도 있을 것 같습니다!

`expiredSeconds` 같이 단위도 붙여주면 더 좋을 것 같네요!

2023-01-26 00:25 UTC, gusah009 commented on src/main/java/com/dinosaur/foodbowl/global/config/security/jwt/JwtAuthenticationFilter.java
> +      HttpServletResponse httpResponse = (HttpServletResponse) response;
@woo-chang `ACCESS_TOKEN`이 만료되었는데 `jwtTokenProvider.extractToken((HttpServletRequest) request, ACCESS_TOKEN)`가 동작하나요? 제가 알기론 만료된 토큰에서 `subject`를 추출하려고 하면 에러가 나는 것으로 알고 있습니다.

2023-01-26 00:28 UTC, JeonghakLee commented on src/main/java/com/dinosaur/foodbowl/global/config/security/jwt/JwtAuthenticationFilter.java
> +      if (refreshTokenValidation.isValid() && tokenService.validate(userId,
accessToken이 expired 이고 refreshToken이 vaild하다는 것을 검증하는 메서드를 추출해봐도 좋을 것 같습니다!

2023-01-26 02:21 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/global/config/security/jwt/JwtAuthenticationFilter.java
> +      HttpServletResponse httpResponse = (HttpServletResponse) response;
저도 처음에는 그것 때문에 고민을 해보았으나 단순히 `Base64`로 인코딩된 `Payload` 내부의 정보가 필요하였기에 토큰을 통해 해당 값을 가져오고자 하였습니다!

만료되어있음이 확인되기에 토큰은 유효한 것이 보장되고 디코딩하여 `userId`를 가져오는 작업이므로예외가 발생하지 않았습니다 .. !

2023-01-26 02:24 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/domain/auth/application/CookieService.java
> +  }
좋습니다 👍👍

2023-01-26 02:24 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/domain/auth/application/CookieService.java
> +@Transactional(readOnly = true)
`service`는 습관적으로 붙여버렸네요 😅

2023-01-26 02:31 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/global/config/security/SecurityConfiguration.java
> +  private final JwtAuthenticationFilter jwtAuthenticationFilter;
커밋 메시지를 잘못 작성한 것 같습니다 😅

생성자를 통한 빈 등록이 아닌 컴포넌트 스캔을 통한 빈 등록이 적절한 것 같습니다!

2023-01-26 02:32 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/global/config/security/jwt/JwtAuthenticationFilter.java
> +          refreshTokenValidation.getToken())) {
감사합니다 👍👍

2023-01-26 02:43 UTC, woo-chang commented
> `JwtAuthenticationFilter`에서 하는 역할이 너무 많은 것 같은데, `RefreshTokenFilter` 같은 필터를 하나 더 두는 건 어떻게 생각하시나요?
> 
> Ex) [KEEPER31337/Homepage-Back-R2#28](https://github.com/KEEPER31337/Homepage-Back-R2/pull/28)

좋은 의견 감사합니다 !!
저는 우선적으로 `RT`까지 검증하는 것이 JwtAuthenticationFilter`에서 하는 역할이라고 생각하였습니다. 그래서 한 곳에 있어야 오히려 이해하기 쉬운 느낌이 들었습니다. 다음으로는 `req`에서 `AT`를 추출하는 중복적인 동작이 발생한다고 생각했습니다. 그래서 한 곳에 있는 것도 나쁘지 않다는 생각이 들었는데 어떤게 좋을지는 아직 와닿지는 않습니다 🤔

2023-01-26 02:51 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/global/config/security/jwt/JwtAuthenticationFilter.java
> +      if (refreshTokenValidation.isValid() && tokenService.validate(userId,
좋은 의견 감사합니다!!
`accessToken이 expired 이고 refreshToken이 vaild하다는 것`을 묶어버리면 refreshToken 추출이 요청마다 발생해야할 것 같습니다. 하지만 accessToken이 expired할 때만 refreshToken 추출이 필요해서 위와 같이 작성했습니다.

혹시 어떤 식으로 진행할지 예시 한번 들어주실 수 있을까요?

2023-01-26 05:02 UTC, gusah009 commented on src/main/java/com/dinosaur/foodbowl/global/config/security/jwt/JwtAuthenticationFilter.java
> +        String accessToken = tokenService.createAccessToken(userId, RoleType.ROLE_회원);
접근하는 회원의 권한이 `ROLE_회원`이 아닐 때도 `ROLE_회원`이 들어가나요??

2023-01-26 08:57 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/global/config/security/jwt/JwtAuthenticationFilter.java
> +        String accessToken = tokenService.createAccessToken(userId, RoleType.ROLE_회원);
꼼꼼한 리뷰 감사합니다 .. ⛄️

2023-01-26 12:20 UTC, gusah009 approved these changes
고생많으셨습니다 ㅠㅠㅠㅠ

2023-01-26 23:53 UTC, JeonghakLee commented on src/main/java/com/dinosaur/foodbowl/global/config/security/jwt/JwtAuthenticationFilter.java
> +      if (refreshTokenValidation.isValid() && tokenService.validate(userId,
if, else if, else 로 분기를 나누신 부분을 따로 메서드 추출해서 길어진 코드의 가독성을 높여봐도 괜찮을 것 같아서 말씀드렸던 것 같습니다!

2023-01-26 23:56 UTC, JeonghakLee approved these changes
수고하셨습니다 쉽지않네요..!!!

2023-01-27 04:00 UTC, merged