Feature/#20 게시글 작성 기능을 구현한다
Busan-Dinosaur/FoodBowl-Server pull request #78
Opened 2023-01-29 07:26 UTC by JeonghakLee

## 🔥 Related Issue

close: #20 

## 📝 Description

게시글 작성 기능 구현

## 🌟 Review

사진 저장 기능 구현 시급

2023-01-29 08:12 UTC, gusah009 reviewed
수고 많으셨습니다~!

2023-01-29 08:12 UTC, gusah009 commented on src/main/java/com/dinosaur/foodbowl/domain/store/dto/StoreDto.java
> +  private Category category;
`Category` 엔티티를 받는 것 같습니다!

2023-01-29 08:12 UTC, gusah009 commented on src/main/java/com/dinosaur/foodbowl/domain/address/dto/AddressDto.java
>  public class AddressDto {
빌더 때문에 `@AllArgsConstructor`를 넣으신거라면 `AccessLevel`을 낮춰도 될 것 같습니다!

2023-01-29 08:12 UTC, gusah009 commented on src/test/java/com/dinosaur/foodbowl/domain/post/application/PostServiceTest.java
> +          .isInstanceOf(IndexOutOfBoundsException.class);
`IndexOutOfBoundsException`은 **"사진이 없으면 게시글 생성에 실패한다"**와 조금은 관련이 멀어보이는 `Exception`인 것 같습니다!

비즈니스 `Exception`으로 바꾸는 건 어떨까요?

2023-01-29 08:12 UTC, gusah009 commented on src/main/java/com/dinosaur/foodbowl/domain/post/dto/PostCreateResponseDto.java
> +  }
메서드 네임으로 `of`보다 `from`이 더 좋을 것 같습니다!

2023-01-29 08:12 UTC, gusah009 commented on src/main/java/com/dinosaur/foodbowl/domain/post/api/PostController.java
> +      @Valid @RequestPart PostCreateRequestDto request) {
왜 `PostCreateRequestDto`에 있던 필드를 `images`로 뺐는 지 알 수 있을까요?

2023-01-29 08:12 UTC, gusah009 commented on src/test/java/com/dinosaur/foodbowl/domain/post/api/PostControllerTest.java
> +      doReturn(userId).when(authUtil).getUserIdByJWT();
이 부분은 우창님의 `@LoginUser`로 바꿀 수 있을 것 같습니다!

2023-01-29 10:16 UTC, JeonghakLee commented on src/main/java/com/dinosaur/foodbowl/domain/address/dto/AddressDto.java
> +public class AddressDto {
모든 필드를 포함하는 dto라 다른 곳에 쓰일 것 같아서 붙이지 않았는데 붙이는 게 나을까요??

2023-01-29 10:19 UTC, JeonghakLee commented on src/main/java/com/dinosaur/foodbowl/domain/post/application/PostService.java
> +  }
게시글 작성 시 사진 최소 한장은 필수라 해당 사진에 대한 썸네일은 반드시 있을 것 같습니다.
+ 추가적으로 컨트롤러에서 사진이 없으면 잘못된 요청으로 처리해서 서비스에서 굳이 검증 로직을 두지 않았습니다

2023-01-29 10:21 UTC, JeonghakLee commented on src/main/java/com/dinosaur/foodbowl/domain/store/dto/StoreDto.java
> +  private Category category;
[여기](https://github.com/Busan-Dinosaur/FoodBowl-Server/pull/78/commits/81e06b5d30edd0befa8acc61f66bcdea30dd9b5c)서 수정했습니다!

2023-01-29 10:22 UTC, JeonghakLee commented on src/test/java/com/dinosaur/foodbowl/domain/post/application/PostServiceTest.java
> +          .isInstanceOf(IndexOutOfBoundsException.class);
컨트롤러에서 사진이 없으면 잘못된 요청으로 처리해서 서비스에서 굳이 검증 로직을 두지 않았는데 
검증 로직을 두고 예외 처리를 하는 편이 나을까요??

2023-01-29 10:27 UTC, JeonghakLee commented on src/main/java/com/dinosaur/foodbowl/domain/post/api/PostController.java
> +      @Valid @RequestPart PostCreateRequestDto request) {
ControllerTest에서 param을 하나 하나 작성하기보다 이미지와, dto를 바로 요청에 넣는 방법이 없을까해서 찾아 보다가 이렇게 작성했습니다!

2023-01-29 11:54 UTC, gusah009 commented on src/main/java/com/dinosaur/foodbowl/domain/address/dto/AddressDto.java
> +public class AddressDto {
넵 `class`가 많아지더라도 `request`, `response` dto는 최대한 재사용하지 않는게 유지보수하기 좋더라구요..!

2023-01-29 11:54 UTC, gusah009 commented on src/main/java/com/dinosaur/foodbowl/domain/post/application/PostService.java
> +  }
아하 그런데 서비스 코드에선 따로 그런 로직이 없어서 여쭤봤습니다!

2023-01-29 12:05 UTC, gusah009 commented on src/test/java/com/dinosaur/foodbowl/domain/post/application/PostServiceTest.java
> +          .isInstanceOf(IndexOutOfBoundsException.class);
서비스 코드 재사용 문제도 있고 해서 엄격하게 따지면 컨트롤러와 도메인 로직은 분리해서 둘 다 검증 로직을 두는게 맞다고 생각하는데, 이것저것 다 따지면서 개발하기 빡셀 것 같긴 하네요... 

서비스에 검증 로직을 넣지 않는다 하더라도 `IndexOutOfBoundsException.class`보단 다른 `Exception`이 더 좋을 것 같습니다! 😅

2023-01-29 13:38 UTC, woo-chang requested changes
가장 핵심인 기능이라 신경 쓸 부분이 많았을텐데 수고하셨습니다 ⛄️

2023-01-29 13:38 UTC, woo-chang commented on src/docs/post/post.adoc
> +include::{snippets}/create-post/response-body.adoc[]
`docs` -> `docs/asciidoc`으로 디렉토리 이동으로 인해 충돌 발생할 수 있을 것 같습니다!

현재 `develop` 병합 후에 확인 한번 부탁드립니다~

2023-01-29 13:38 UTC, woo-chang commented on src/docs/post/post.adoc
> +include::{snippets}/create-post/http-request.adoc[]
주체가 앞으로 와야 여러 개가 생겨도 한번에 확인할 수 있을 것 같아서 `post-create` 요런식으로 맞춰주시면 감사합니다 ⛄️

2023-01-29 13:38 UTC, woo-chang commented on src/docs/post/post.adoc
> +== *게시글*
**게시글 생성**으로 명확하게 알려줘야 클라이언트에서 쉽게 확인할 수 있을 것 같습니다!

2023-01-29 13:38 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/domain/post/api/PostController.java
> +        .body(PostCreateResponseDto.of(postId));
`CREATED`를 사용하시면 단순히 `id`만 전달하기보다는

해당 리소스를 확인할 수 있는 `location`을 전달해주는 것이 좋을 것 같습니다!

2023-01-29 13:38 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/domain/post/application/PostService.java
> +    List<Photo> photos = photoUtil.save(images);
각 파일들이 `image`인지 확인하는 코드도 필요해보입니다 ..!

2023-01-29 13:38 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/domain/post/application/PostService.java
> +    Category category = categoryRepository.getReferenceById(postCreateRequestDto.getCategoryId());
카테고리 여러 개로 받을 수 있는 것으로 변경되어 수정이 필요할 것 같습니다 😅

2023-01-29 13:38 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/domain/post/application/PostService.java
> +  }
`StoreFindDao`로 역할을 분리해봐도 좋을 것 같습니다 🤔

2023-01-29 13:38 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/domain/post/application/PostService.java
> +  }
이런 작은 메서드들은 분리하는 것보다 `Util`을 바로 사용하는 것이 직관적으로 와닿던데

정학님 생각은 어떠신지 궁금합니다!

2023-01-29 13:38 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/global/util/photo/PhotoFileUtil.java
> +  public List<Photo> save(List<MultipartFile> files) {
이 부분은 다른 `issue`로 해결하시는건가요?

2023-01-29 23:39 UTC, JeonghakLee commented on src/main/java/com/dinosaur/foodbowl/domain/post/application/PostService.java
> +    List<Photo> photos = photoUtil.save(images);
photoUtil이 해야할 역할이라고 생각해서 하지 않았는데 여기서 하는게 좋을까요??

2023-01-29 23:43 UTC, JeonghakLee commented on src/main/java/com/dinosaur/foodbowl/global/util/photo/PhotoFileUtil.java
> +  public List<Photo> save(List<MultipartFile> files) {
네 `#27 사진 저장하는 기능을 구현한다` 에서 하려고 했습니다!

2023-01-30 15:01 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/domain/post/application/PostService.java
> +    List<Photo> photos = photoUtil.save(images);
해당 이슈에서 처리할 계획이시면 그쪽이 맞을 것 같습니다 👍🏻

2023-02-01 01:30 UTC, gusah009 approved these changes
수고많으셨습니다!

2023-02-23 14:32 UTC, merged