Feature/#27 사진 저장하는 기능을 구현한다
Busan-Dinosaur/FoodBowl-Server pull request #87
Opened 2023-02-02 11:02 UTC by JeonghakLee

## 🔥 연관 이슈

close: #27

## 📝 작업 요약

사진 저장, 삭제 서비스 구현

## 🔎 작업 상세 설명

## 🌟 리뷰 요구 사항
- 사진을 굳이 리사이징 할 필요 없을 것 같아서 구현하지 않았습니다.
- 추후 문제가 된다면 최대 크기를 정해두고 넘는 것들만 리사이징 해보는 것도 괜찮을 것 같습니다.

2023-02-03 00:55 UTC, gusah009 approved these changes
👏👏👏👏👏👏 수고많으셨습니다!

2023-02-03 02:56 UTC, woo-chang requested changes
어려운 작업이었을텐데 고생하셨습니다! 메서드를 분리하기 위해 고민한 코드들이 보입니다 ㅎㅎ

수정 사항 확인 부탁드립니다 ⛄️

2023-02-03 02:56 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/domain/photo/application/PhotoService.java
> +@Slf4j
사용하지 않는 어노테이션은 제거하는 게 좋을 것 같아요 ⛄️

2023-02-03 02:56 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/domain/photo/application/file/PhotoFileService.java
> +  private static final String DEFAULT_PHOTO_PATH = RESOURCE_PATH + "photo" + separator;
`31`~`34`의 상수들은 별도로 관리하는건 어떨까요 ? ?

2023-02-03 02:56 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/domain/photo/application/file/PhotoFileService.java
> +  }
가독성을 위해 사용되는 곳 아래로 메서드를 옮겨주시면 감사합니다 😎

2023-02-03 02:56 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/domain/photo/application/file/PhotoFileService.java
> +      throw new IllegalArgumentException("파일이 이미지가 아닙니다. 파일 이름: " + file.getOriginalFilename());
BusinessException을 사용하고 있는만큼 BusinessException을 사용하는게 좋을 것 같습니다!

2023-02-03 02:56 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/domain/photo/application/file/PhotoFileService.java
> +  public Photo save(MultipartFile file, Post post) throws IOException {
`IOException`도 그냥 던지기 보다는 잡아서 처리가 필요할 것 같습니다!

2023-02-03 02:56 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/domain/photo/application/file/PhotoFileService.java
> +      throw new IllegalArgumentException("파일 이름 길이가 너무 깁니다. 가능한 파일 이름 길이: " +
여기도 BusinessException을 사용하는게 좋을 것 같습니다!

2023-02-03 02:56 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/domain/photo/application/file/PhotoFileService.java
> +      Files.deleteIfExists(Path.of(ROOT_PATH + photo.getPath()));
삭제 시 파일도 바로 삭제하도록 하네요!

이 부분도 고민이여서 같이 얘기해보고 싶었는데, `IO`가 들어가는 작업이라
사용자가 적은 새벽 시간에 `DB`에 없는 사진들은 배치 작업으로 한 번에 지우는게 나은지, 아니면 path 바로 찾을 수 있으니까 즉각적으로 바로 지우는게 나은지 궁금합니다! 정학님은 어떻게 생각하시나요?

2023-02-03 02:56 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/domain/photo/application/file/PhotoFileService.java
> +  public Photo save(MultipartFile file, Post post) throws IOException {
`MultipartFile`에 null이 들어가면 어떤 상황이 발생하나요?

2023-02-03 02:56 UTC, woo-chang commented on src/test/java/com/dinosaur/foodbowl/domain/photo/application/file/PhotoFileServiceTest.java
> +    }
테스트 후 정리하는 코드 좋습니다 👍👍

2023-02-03 02:56 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/domain/photo/application/file/PhotoFileService.java
> +  public Photo save(MultipartFile file, Post post) throws IOException {
`DB`에 존재하지 않는 `Post`인 경우에는 어떤 상황이 발생하나요?

2023-02-03 02:56 UTC, woo-chang commented on src/test/java/com/dinosaur/foodbowl/domain/photo/application/file/PhotoFileServiceTest.java
> +  }
사진 파일이 존재하지 않을 경우 어떤 상황이 발생하는지 테스트 하는 것도 좋을 것 같습니다!

2023-02-03 05:05 UTC, JeonghakLee commented on src/main/java/com/dinosaur/foodbowl/domain/photo/application/file/PhotoFileService.java
> +      Files.deleteIfExists(Path.of(ROOT_PATH + photo.getPath()));
테스트 해볼 때도 느꼈는데 File IO 시간이 성능에 영향을 많이 미쳐서 한번에 지우는게 좋을 것 같습니다! 
이 메서드는 배치 작업시 사용해도 되지 않을까요??

2023-02-03 05:10 UTC, JeonghakLee commented on src/main/java/com/dinosaur/foodbowl/domain/photo/application/file/PhotoFileService.java
> +  public Photo save(MultipartFile file, Post post) throws IOException {
꼼꼼한 리뷰 감사합니다! 다 처리가 필요한 부분들이네요👍👍👍

2023-02-03 10:57 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/domain/photo/application/file/PhotoFileService.java
> +      Files.deleteIfExists(Path.of(ROOT_PATH + photo.getPath()));
눈에 보일 정도로 성능에 영향을 주는군요 .. ! 좋은 의견 감사합니다 ⛄️

2023-02-05 11:59 UTC, woo-chang reviewed
리뷰가 반영되지 않은 부분이 조금 있는 것 같아서 확인 부탁드립니다 ⛄️

2023-02-05 11:59 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/domain/photo/application/file/PhotoFileService.java
> +  private static final String DEFAULT_PHOTO_PATH = RESOURCE_PATH + "photo" + separator;
이 부분은 그대로 유지하시는건가요?  👀

2023-02-05 11:59 UTC, woo-chang commented on src/main/java/com/dinosaur/foodbowl/domain/photo/application/file/PhotoFileService.java
>    private static void checkPhotoFullPathLength(String photoFullPath, String fileName) {
여기도 `IllegalArgumentException` 그대로 사용하시는건가요? 👀

2023-02-05 11:59 UTC, woo-chang commented on src/test/java/com/dinosaur/foodbowl/domain/photo/application/file/PhotoFileServiceTest.java
>      private void deleteTestFile(Photo photo) {
사진 파일이 존재하지 않을 경우 어떻게 되는지 궁금합니다 👀

2023-02-11 00:27 UTC, woo-chang approved these changes
수고하셨습니다 👍👍

2023-02-11 00:27 UTC, merged